### PR TITLE
reduced size

### PR DESCRIPTION
**Pull request by danielrohe**
These changes reduce the size of the image to less than 10 megabytes.

### CODE REVIEW

**Comment by hjacobs** [comment]
OK, can you somehow prove that it works? (console output, some openssl s_client -connect against RDS ...)

**Comment by danielrohe** [comment]
Attached is a screenshot that shows the certificates and the content of one
docker-alpine-aws-certs
.

**Comment by hjacobs** [comment]
@danielrohe can you fix the double file extension?

**Comment by danielrohe** [comment]
@hjacobs looks strange but works

**Pull request merged**
